name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Extract information
        id: package
        shell: bash
        run: |
          PROJECT_VERSION=$(echo $(sed -n 's/"version": "\(.*\)",/\1/p' extension.json | head -n1))
          PROJECT_NAME=$(echo $(sed -n 's/"name": "\(.*\)",/\1/p' extension.json | head -n1))
          PKG_NAME=${PROJECT_NAME}-master-v${PROJECT_VERSION}.tar.gz
          echo ::set-output name=PKG_NAME::${PKG_NAME}
          echo ::set-output name=PROJECT_NAME::${PROJECT_NAME}
      - name: zip
        run: |
          mkdir ${{ steps.package.outputs.PROJECT_NAME }}
          cp -r i18n/ README.md Lazyload.class.php extension.json ${{ steps.package.outputs.PROJECT_NAME }}
          tar -czvf ${{ steps.package.outputs.PKG_NAME }} Lazyload
      - name: "Artifact upload: tarball"
        uses: actions/upload-artifact@master
        with:
          name: ${{ steps.package.outputs.PKG_NAME }}
          path: ${{ steps.package.outputs.PKG_NAME }}
      - name: "Artifact upload: tarball"
        uses: actions/upload-artifact@master
        with:
          name: ${{ steps.package.outputs.PKG_NAME }}
          path: ${{ steps.package.outputs.PKG_NAME }}
      - name: Publish archives and packages
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.package.outputs.PKG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
